### ISSUE TITLE
크롬에서 출력되는 오?류 제보

### ISSUE THREAD

**Issue by SameDesu123** [Zabee52/Wakfreeca#106]

**Comment by Zabee52** [comment]
음.. 보안 관련된 requirements가 변경된 것 같군요.. 확인해보겠습니다. 제보 감사합니다! (__)

**Comment by Zabee52** [comment]
첫 번째 이미지에 관하여: 추가 확인 후 업데이트 하겠습니다 (__)

두 번째 이미지에 관하여: Wakfreeca 패키지 구성요소에는 `_metadata` 파일이나 디렉토리가 존재하지 않기 때문에 동작에는 문제가 없을 것으로 보입니다. 이 에러 메세지는 크롬 익스텐션 스토어에 관한 널리 알려진 이슈(스토어 자체의 버그)라고 합니다. (10년 정도 되었다고 합니다 😅)

**Comment by Zabee52** [comment]
첫 번째 이미지에 관한 사유는 어떻게 해야 알람을 제거할 수 있는지 찾아봤는데 특별한 단서를 찾지 못 했습니다. 🫠
동작에는 문제가 없으니, 해결할 방법을 지속적으로 찾아보겠습니다. (__)

**Comment by SameDesu123** [comment]
<img width="413" alt="스크린샷 2024-02-12 18 03 32" src="https://github.com/Zabee52/Wakfreeca/assets/47582414/5d7548b6-9e50-4274-800e-75151f5a6623">
첫 번째 이미지에서 나오는 알림은 2.0.1로 업데이트하고 나서 사라졌습니다
