### ISSUE TITLE
[Chat] ㄱㅇㅇ 필터 별도 분리

### ISSUE THREAD

**Issue by adcviper** [Zabee52/Wakfreeca#129]
제목 그대로 ㄱㅇㅇ 필터 사용 시

헉 <<< 도 필터링 되는 버그가 있는 것 같습니다!

채팅에 헉을 치면 안보이다가

필터를 끄면 보여요!

+++++++추가

지금 확인했는데 '헉'만 안보이는게 아니라

헉, 엥, 1, 2, ?, 와, 오 같은

한글자 채팅 전부가 필터링에 걸려서 안보이는 것 같아요 ㅠㅠ

**Comment by Zabee52** [comment]
사실은 기능의 이름이 ㄱㅇㅇ 필터이지만, 제가 개인 편의성을 위해 만든 기능에 필터 기준을 추가로 빠르게 붙여넣고 출시했던 것이어서 몇 가지 정책이 동시에 섞여있습니다. 😊
- 필터링 대상 : ㄱㅇㅇ, ㅋㅋㅋㅋㅋ..., 1글자 채팅, ㄹㅇ

이번 주 중으로 필터링 대상을 구분하는 작업을 수행할 예정으로, 완료 후에 업데이트 드리겠습니다. (__)

**Comment by adcviper** [comment]
이렇게 빨리 확인해주시다니 감사합니다! 너무 잘 쓰고 있어요!!! 덕분에 시청이 한껏 편리합니다 감사합니다!! 항상 좋은 일만 가득하세요 : )

**Comment by Zabee52** [comment]
우선 당장 사용할 수 있도록 분리 해두었습니다. (__)
![image](https://github.com/Zabee52/Wakfreeca/assets/93498724/69457e6f-bf13-48ad-abfe-e5ff1098780a)
