### ISSUE TITLE
[Chat] 채팅 필터링 커스텀 기능

### ISSUE THREAD

**Issue by gldi80** [Zabee52/Wakfreeca#130]
우선 리뷰에도 썼지만 못보실까봐 여기다가도 씁니다

ㄱㅇㅇ필터 만들어 주신거 정말 감사드립니다.

캬ㅑㅑㅑ 도 같이 필터 됐으면 좋겠습니다

ㅋㅋㅋㅋㅋㅋ 는 같이 웃고싶을때가 더 많아서 필터 해제하는 항목 있으면 좋을 거 같습니다.

**Comment by Zabee52** [comment]
한 다음 주 정도까지 필터링 리스트를 개인적으로 설정할 수 있도록 추가해 두고 업데이트 드리겠습니다. 건의 감사합니다 (__)

**Comment by idoidoi** [comment]
ㅔㅔ도 추가 부탁드려요 
ㄱㅇㅇ 없으니깐 너무 보기 좋아요 킹애~

**Comment by Zabee52** [comment]
우선 당장 사용할 수 있도록 ㄱㅇㅇ, ㅔㅔ, 캬ㅑ 채팅은 분리해두었습니다. (__)
![image](https://github.com/Zabee52/Wakfreeca/assets/93498724/252bd926-ebdc-4363-a9fe-5d02c15691ae)
