### ISSUE TITLE
사용자가 직접 단어 설정해서 필터링 되게하는건 어려운가요?

### ISSUE THREAD

**Issue by wijlgjb** [Zabee52/Wakfreeca#133]
어렵다면 ㅗ 필터 추가 가능할까요? 밈이란건 알지만 보기 힘든건 힘든거라...

**Comment by Zabee52** [comment]
안녕하세요. 개발자입니다.
직접 설정하는 기능은 개발 예정으로, 아마 여유가 있다면 다음주 주말까지는 추가될 것 같습니다.
1글자 단어의 경우 클린채터 설정을 활성화 시켜주신다면 필터링이 될 겁니다!

fyi. https://github.com/Zabee52/Wakfreeca/issues/130
