### ISSUE TITLE
추가건의~~

### ISSUE THREAD

**Issue by gldi80** [Zabee52/Wakfreeca#142]
우선 제가 뭐 후원하는것도 아니고 잘 쓰고 있는 입장에서 건의만 해서 죄송합니다

1. 캬ㅑ 필터 체크했는데 그냥 캬 , ㅋ캬ㅑ 등등 필터링이 안되는 채팅이 존재합니다
캬ㅑ가 시작이 아닌 어느 부분에 있더라도 채팅안에 ' 캬 ' < 이 단어가 포함되면 필터링 되게 할 수 있나요??

2. ㄱㅇㅇ 필터링은 잘 작동합니다만 요즘 사람들이 이걸 알고있어서 일부러 그러는지 ㅇㅇㄱ 혹은 ㄱㅇㅇㄱㅇㅇ 등등 필터링에
안걸리게 교묘하게 치는사람들이 생각보다 많습니다 이것도 필터링되면 좋을거같아요

감사합니다 항상 수고 많으십니다.

**Comment by Zabee52** [comment]
안녕하세요, 해당 기능에서 커스텀하여 사용할 수 있도록 추가 예정입니다. : https://github.com/Zabee52/Wakfreeca/issues/130
