### ISSUE TITLE
[Chat] 닉네임이 채팅창 바깥까지 표시됨

### ISSUE THREAD

**Issue by SameDesu123** [Zabee52/Wakfreeca#148]

**Comment by Zabee52** [comment]
안녕하세요! 제보 감사드립니다 (__)
음... 보기에는 위의 레이아웃을 제공하는 익스텐션의 버그로 보입니다. (넘어간 칸과 해당 섹션의 높이가 동일한 점을 통하여 추측했습니다.)

![image](https://github.com/Zabee52/Wakfreeca/assets/93498724/8095d9eb-e78d-4e66-a59f-0f0d1cf51b39)

혹시 해당 레이아웃을 숨긴 상태에서도 같은 증상이 발생하는지 확인 부탁드려도 될까요?
