### ISSUE TITLE
[BUG] 채팅 크기 설정 

### ISSUE THREAD

**Issue by khj1222** [Zabee52/Wakfreeca#40]
안녕하십니까

아래 캡쳐된 사진 처럼 채팅 크기 설정을 변경 하더라도 줄간 간격만 멀어질뿐 크기가 커지지 않는 버그가 있는것 같습니다.

감사합니다.

![image](https://github.com/Zabee52/Wakfreeca/assets/39723594/391223bb-6f3c-40b9-b937-b0f3766148e3)

**Comment by Zabee52** [comment]
https://github.com/Zabee52/Wakfreeca/issues/45
해당 카드에서 작업하겠습니다. 피드백 감사합니다! 🙇

**Comment by Zabee52** [comment]
완료. 다음 배포에 반영될 예정입니다.
