### ISSUE TITLE
[Chat] 매니저 상태에서 유저 아이디 크기가 다르게 보임

### ISSUE THREAD

**Issue by SameDesu123** [Zabee52/Wakfreeca#48]

**Comment by Zabee52** [comment]
닉네임에 bold 적용을 위해 별도의 element를 생성하도록 코드가 작성되어 있었는데, 이제는 정상적으로 style을 상속받도록 수정했습니다.

https://github.com/Zabee52/Wakfreeca/issues/45
해당 이슈가 해결되면서 함께 처리될 예정입니다. 제보 감사합니다! 🙇
