### ISSUE TITLE
[Chat] 채팅에 간격이 생기는 문제

### ISSUE THREAD

**Issue by SameDesu123** [Zabee52/Wakfreeca#87]

**Comment by Zabee52** [comment]
채팅 한 줄로 보기 기능 사용 중, 신고가 정상적으로 이루어지지 않는 문제 https://github.com/Zabee52/Wakfreeca/issues/84
해당 문제를 수정하는 과정에서 생긴 사이드 이펙트로, 기존 구조에서는 `dd` element는 두 줄일때에만 나타났기 때문에 좌측 공백 존치 여부를 결정하는 컨디션이 달랐던 문제입니다. 오늘 중에 수정 예정입니다. 제보 감사합니다 (__)

**Comment by Zabee52** [comment]
수정 완료됐습니다. 1시간 이내에 배포될 예정입니다. https://github.com/Zabee52/Wakfreeca/pull/88
